# Laboratory techniques for DNA extraction 

```{block, type='objectives'}

**Objectives**

1. To learn about bacterial genomic DNA extraction
2. To understand the biochemical process of cell rupture and DNA elution
3. To identify good quality genomic DNA extractions from isolated samples

```


We use a DNA extraction kit (Monarch Genomic DNA Purification Kit) to obtain  high molecular weight genomic DNA. The protocol can be found [here](https://www.neb.com/-/media/nebus/files/manuals/manualt3010.pdf?rev=63c286659d6e44dc8637b2ae4f9effa4&hash=26A4B9D0E51C6793FF460365DC92B6EE) or in our Canvas page. 

**Read pages 4-5 and 12-13 before coming to the lab so you can familiarize yourself with the protocol**


## Protocol using G/20 QIAGEN columns

1.	Harvest a maximum of up to 2 x 109 Gram-negative bacteria by centrifugation for 1 minute at> 12,000 x g. Discard supernatant.

2.	Add 90 µL of cold PBS or 10 mM Tris-Cl pH 8.0 and resuspend bacterial pellet by vortexing or pipetting up and down.

3.	Add 10 µL Lysozyme solution (25 mg/ml) and vortex briefly, then add 100 µL Tissue Lysis Buffer and vortex thoroughly.

4.	Incubate at 37°C for 5 minutes or until clear. Most lysates will become fully clear, but for some bacteria a slight haze may remain.

5.	Add 10 µL Proteinase K, vortex briefly, and incubate at 56°C for a minimum of 30 minutes in a thermal mixer with agitation at full speed.

```{block, type='rmderror'}
At this time, go to the **Analytical gel for DNA integrity and fragment size** section and start your gel.
```

6.	Add 3 µL of RNase A to the lysate, vortex briefly, and incubate for a minimum of 5 minutes at 56°C with agitation at full speed (~1400 rpm).

7.	Add 400 µL gDNA Binding Buffer to the sample and mix thoroughly by pulse-vortexing for 5-10 seconds. Thorough mixing is essential for optimal results.

8.	Transfer the lysate/binding buffer mix (~600 µL) to a gDNA Purification Column pre-inserted into a collection tube, without touching the upper column area. Proceed immediately to Step 3. Do not reload the same column with more sample

```{block, type='rmdwarning'}
Over-exposure of the matrix to the lysed sample can cause the membrane to expand and dislodge. Avoid touching the upper column area with lysate/binding mix and avoid transferring foam that may have formed during lysis. Any material that touches the upper area of the column, including any foam, may lead to salt contamination in the eluate.
```

9.	Close the cap and centrifuge: first for 3 minutes at 1,000 x g to bind gDNA (no need to empty the collection tubes or remove from centrifuge) and then for 1 minute at maximum speed (> 12,000 x g) to clear the membrane. 

10.	Discard the flow-through and the collection tube. For optimal results, ensure that the spin column is placed in the centrifuge in the same orientation at each spin step (for example, always with the hinge pointing to the outside of the centrifuge); ensuring the liquid follows the same path through the membrane for binding and elution can slightly improve yield and consistency.

11.	Transfer column to a new collection tube and add 500 µL gDNA Wash Buffer. Close the cap and invert a few times so that the wash buffer reaches the cap. Centrifuge immediately for 1 minute at maximum speed and discard the flow through. The collection tube can be tapped on a paper towel to remove any residual buffer before resulting the next step. Inverting the spin column with wash buffer prevents salt contamination in the eluate.

12.	Reinsert the column into the collection tube. Add 500 µL gDNA Wash Bufer and close the cap. Centrifuge immediately for 1 minute at maximum speed and discard the collecting tube and flow through.

13.	Place the gDNA Purification Column in a DNase-free 1.5 ml microfuge tube (not included). Add 35- 100 µL preheated (60°C) gDNA Elution Buffer, close the cap and incubate at room temperature for 1 minute. Elution in 100 µL is recommended, but smaller volumes can be used and will result in more concentrated DNA but a reduced yield (20-25% reduction when using 35 µL). 

```{block, type='rmdwarning'}
Eluting with preheated elution buffer will increase yields by ~20-40% and eliminates the need for a second elution. For applications in which a high DNA concentration is required, using a small elution volume and then re­eluting with the eluate may increase yield (~10%). The elution buffer (10 mM Tris-Cl, pH 9.0, 0.1 mM EDTA) offers strong protection against enzymatic degradation and is optimal for long term storage of DNA. However, other low-salt buffers or nuclease-free water can be used if preferred. For more details on optimizing elution, please refer to "Considerations for Elution & Storage" (page 4).
```

14.	Centrifuge for 1 minute at maximum speed (> 12,000 x g) to elute the gDNA.

## Quantification of DNA using Qubit and Nanodrop
 
To determine how much DNA we extracted, we will use Qubit and Nanodrop to quantify the amount of DNA extracted.

### Qubit flurescence quantification

1. Add 198 µL of 1x dsDNA HS Qubit reagent in a Qubit tube

2. Add 2 µL of your gDNA into the qubit tube

3. Vortex for 15 seconds and incubate for 2 minutes

4. Go to the Qubit machine and select dsDNA > 1x HS dsDNA > select 1 µL > Measure sample

5. Record your DNA concentration

### Nanodrop DNA quality

1. Take your DNA extraction to the nanodrop room with your TA. Also, bring the gDNA Elution Buffer from the kit

2. Follow the instructions to blank and measure your DNA

3. Record the 260/280, 230/280 and concetration of your sample

4. Take a picture of the extraction curve


## Analytical gel for DNA integrity and fragment size

1. Mix 0.3 g of agarose into 60 ml of 1x TAE buffer

1. Heat the mixture in the microwave for 30s in 5s intervals until the solution is clear. Mix at every interval.

1. Wait for the mix to cool a little and add 5 μl of SYBR SAFE/SYBR GREEN to the mix

1. Add the mixture to the gel box with the comb in it. **Ask your TA/PLA/Professor for help!**

1. Wait 20/30 mins for the gel to solidify.

1. Add 10 μl of DNA ladder 1kb in the first and last wells of the gel

1. Mix 3 μl of the sample with 6μl of DNA loading buffer and load the mix into one of the wells in the gel.

1. Run the gel for 30 minutes at 95 volts.

1. Visualize the gel in the blue light machine, tak

1. Take a picture for your electronic notebook.


## DNA extraction report

```{block, type='rmdquestion'}

In an R markdown file, include the 260/230 values, 260/280 values, the concentration and picture from the Nanodrop and the concentration from the Qubit.

Also include your gel and indicate your DNA size.

Discuss your results, answer these questions and add them to that discussion:

- Is the Nanodrop concentration higher than the Qubit? Why? 
- What are the differences between qubit and nanodrop?
- Would you consider your DNA extraction to be of HMW? 
- Did you extract enough DNA for the Nanopore sequencing of your genome?
```


